version: '3.3'

services:

# Mysql Container

    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"

# Node Container

    node:
        build:
            context: ./node
        environment:
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - NODEJS_API_PORT=${NODEJS_API_PORT}
        ports:
            - "${NODEJS_API_PORT}:${NODEJS_API_PORT}"
        entrypoint: /app/run-passeidireto.sh "node server.js"
        tty: true
        links:
            - mysql

# Nginx Container

    nginx:
        build:
            context: ./nginx
        environment:
            - NGINX_LISTEN_PORT=${NGINX_LISTEN_PORT}
            - NODEJS_API_PORT=${NODEJS_API_PORT}
        ports:
            - "${NGINX_LISTEN_PORT}:${NGINX_LISTEN_PORT}"
        links:
            - node
